### ISSUE TITLE
Please help : Error While running node install 

### ISSUE THREAD

**Issue by raghavchalapathy** [garystafford/meanio-custom-search#1]
Hello I am running on 

Could you please suggest why I am getting the error below 

MAC 14.5.0 Darwin Kernel Version 14.5.0
$ node -v
v4.4.4
$ npm -v
3.9.0

[Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
forking  0
forking  1
forking  2
forking  3
forking  4
forking  5
forking  6
forking  7
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/raghav/nodeJS_Applications/demo/meanio-custom-search/bower_components/jquery/dist/jquery.min.map'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at module.exports (/Users/raghav/nodeJS_Applications/demo/meanio-custom-search/node_modules/meanio/lib/bootstrap.js:31:27)
    at /Users/raghav/nodeJS_Applications/demo/meanio-custom-search/node_modules/meanio/lib/mean.js:20:27
    at Config.onPackageRead (/Users/raghav/nodeJS_Applications/demo/meanio-custom-search/node_modules/meanio/lib/config.js:101:25)
    at Promise.<anonymous> (/Users/raghav/nodeJS_Applications/demo/meanio-custom-search/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)

**Comment by courtyenn** [comment]
Which version of meanio are you using?

Download nvm (Node version manager) and downgrade your node version to 0.10.x. Then uninstall meanio, and re-install. Let me know what your results are.
